// GENERATED by scripts/build-impact-stickers.mjs. Do not edit by hand.
//
// Every achievement in the Code Ninjas IMPACT curriculum, read off the
// franchise Canva export rather than authored here: 218 of them across the
// 43 CREATE levels, each with the name Code Ninjas gave it and the
// level it actually belongs to.
//
// This file used to hold 35 hand-written milestones over belt spot art, with
// invented titles ("First Coder") on artwork that came from a different level
// than the one it claimed. Those are gone. If a sticker's name or level looks
// wrong now, it is wrong in the source folder's manifest, and the fix belongs
// there and in the build script's TITLE_FIXES table.
//
// A ninja earns every achievement in a level when they finish that level.
// DojoLink knows where a ninja is standing and which projects are logged; it
// does not know which in-game actions they took, and the achievements are
// awarded inside MakeCode rather than by us. Level completion is the honest
// approximation and it is the only claim any surface makes.
// See lib/stickerProgress.js for the one definition of "earned".

const a = (belt, level, title) => {
  const id = `${belt.toLowerCase()}-${level}-${title.toLowerCase().replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')}`;
  return { id, belt, level, title, src: `/impact/${id}.png` };
};

export const CREATE_STICKERS = [
  // White belt
  //   Level 1
  a('White', 1, "First Words"),
  a('White', 1, "Hearts, Smiles and Bubbles, Oh My"),
  a('White', 1, "Maestro"),
  a('White', 1, "Painter's Palette"),
  a('White', 1, "Sprite Place at the Sprite Time"),
  //   Level 2
  a('White', 2, "Colorful Language"),
  a('White', 2, "Story Teller"),
  a('White', 2, "That Belongs in a Museum"),
  a('White', 2, "What's in a Name"),
  //   Level 3
  a('White', 3, "Layer Cake"),
  a('White', 3, "Setting the Scene"),
  a('White', 3, "Taking Control"),
  a('White', 3, "Think Inside the Box"),
  //   Level 4
  a('White', 4, "A Whole New Kind of Sprite"),
  a('White', 4, "Making a Connection"),
  a('White', 4, "Right Behind You"),
  a('White', 4, "SFX"),
  a('White', 4, "The End of the Road"),

  // Yellow belt
  //   Level 1
  a('Yellow', 1, "Keeping Track"),
  a('Yellow', 1, "POOF"),
  a('Yellow', 1, "Time Flies"),
  a('Yellow', 1, "YOLO"),
  //   Level 2
  a('Yellow', 2, "Button Masher"),
  a('Yellow', 2, "I Like to Move It, Move It"),
  a('Yellow', 2, "Pew Pew"),
  a('Yellow', 2, "Pick a Number, Any Number"),
  a('Yellow', 2, "Sugar Rush"),
  a('Yellow', 2, "The Times, They Are a Changin'"),
  //   Level 3
  a('Yellow', 3, "Backup Plan"),
  a('Yellow', 3, "Coin Toss"),
  a('Yellow', 3, "Coming From Left Field"),
  a('Yellow', 3, "Same Difference"),
  a('Yellow', 3, "To Be or Not to Be"),
  //   Level 4
  a('Yellow', 4, "On and On and On And"),
  a('Yellow', 4, "Original Score"),
  a('Yellow', 4, "Saturday Morning Cartoons"),

  // Orange belt
  //   Level 1
  a('Orange', 1, "Assigned Seating"),
  a('Orange', 1, "Charting a Course"),
  a('Orange', 1, "Paparazzi"),
  a('Orange', 1, "Shake it Like a Polaroid"),
  a('Orange', 1, "X and Y Marks the Spot"),
  //   Level 2
  a('Orange', 2, "Birthday Party"),
  a('Orange', 2, "Farewell Party"),
  a('Orange', 2, "New Tile Who Dis"),
  a('Orange', 2, "Ticking Clock"),
  a('Orange', 2, "Trip Wire"),
  a('Orange', 2, "Watch Out For That"),
  //   Level 3
  a('Orange', 3, "Art Critic"),
  a('Orange', 3, "Dictionary"),
  a('Orange', 3, "Making a List"),
  a('Orange', 3, "Results May Vary"),
  a('Orange', 3, "So Happy Together"),
  //   Level 4
  a('Orange', 4, "Button Down"),
  a('Orange', 4, "Freeze Tag"),
  a('Orange', 4, "Once More, With Feeling"),
  a('Orange', 4, "Roll Call"),
  a('Orange', 4, "Yearbook"),
  //   Level 5
  a('Orange', 5, "Area Code"),
  a('Orange', 5, "Customize Your Own Way"),
  a('Orange', 5, "Don't Forget to Call"),
  a('Orange', 5, "Make Your Own Way"),

  // Green belt
  //   Level 1
  a('Green', 1, "Defying Gravity"),
  a('Green', 1, "Hop, Skip and a Jump"),
  a('Green', 1, "Wallflower"),
  //   Level 2
  a('Green', 2, "All or Nothing"),
  a('Green', 2, "Fork in the Road"),
  a('Green', 2, "Know Your Surroundings"),
  a('Green', 2, "Math Magician"),
  a('Green', 2, "Nuh Uh"),
  a('Green', 2, "Splat"),
  a('Green', 2, "Yes-No Question"),
  //   Level 3
  a('Green', 3, "Card Catalog"),
  a('Green', 3, "Waiting for Things to Change"),
  //   Level 4
  a('Green', 4, "Area Rug"),
  a('Green', 4, "Atlas"),
  a('Green', 4, "Ducks in a Row (Or Column)"),
  a('Green', 4, "GPS"),
  a('Green', 4, "Neighbors"),
  //   Level 5
  a('Green', 5, "One Direction"),
  a('Green', 5, "Setting the Bar"),
  a('Green', 5, "Status Symbol"),
  a('Green', 5, "Sticky Tack"),

  // Blue belt
  //   Level 1
  a('Blue', 1, "Coordinating Coordinates"),
  a('Blue', 1, "Gaining a Following"),
  a('Blue', 1, "Opening Line"),
  a('Blue', 1, "Palette Cleanser"),
  a('Blue', 1, "String Theory"),
  a('Blue', 1, "Truth Hurts"),
  //   Level 2
  a('Blue', 2, "A Speedy Recovery"),
  a('Blue', 2, "Comment, Like and Subscribe"),
  a('Blue', 2, "Effective Immediately"),
  a('Blue', 2, "Music to My Ears"),
  a('Blue', 2, "Say What Now?"),
  a('Blue', 2, "Stop and Smell The Roses"),
  a('Blue', 2, "To Whom it May Concern"),
  a('Blue', 2, "Wall of Text"),
  //   Level 3
  a('Blue', 3, "About Yay High"),
  a('Blue', 3, "Cute as a Button"),
  a('Blue', 3, "Framing the Discussion"),
  a('Blue', 3, "Game On"),
  a('Blue', 3, "Projectile Manager"),
  a('Blue', 3, "Settle Score"),
  //   Level 4
  a('Blue', 4, "A Flair for the Dramatic"),
  a('Blue', 4, "Gaming the System"),
  a('Blue', 4, "Hey I'm Walking Here"),
  a('Blue', 4, "If At First You Don't Succeed"),
  a('Blue', 4, "Let's Try That Again"),
  a('Blue', 4, "Nestled Brackets"),
  a('Blue', 4, "Playing the Odds"),
  a('Blue', 4, "The Final Countdown"),
  a('Blue', 4, "Until the End of Time"),
  //   Level 5
  a('Blue', 5, "Asset Depreciation"),
  a('Blue', 5, "Concentration Station"),
  a('Blue', 5, "I'm Thinking of a Number"),
  a('Blue', 5, "Incremental Growth"),
  a('Blue', 5, "It's Back on the Menu"),
  a('Blue', 5, "Let There Be Variables"),
  //   Level 6
  a('Blue', 6, "Comparatively Speaking"),
  a('Blue', 6, "Hard Pressed"),
  a('Blue', 6, "Package Deal"),
  a('Blue', 6, "Reassess the Situation"),
  a('Blue', 6, "This or That"),

  // Purple belt
  //   Level 1
  a('Purple', 1, "A Meeting of the Kinds"),
  a('Purple', 1, "From One Sprite to Another"),
  a('Purple', 1, "Kind of You to Join"),
  a('Purple', 1, "Life of the Party"),
  a('Purple', 1, "Metamorphosis"),
  a('Purple', 1, "New Kind on the Block"),
  a('Purple', 1, "Nice Knowing Ya"),
  a('Purple', 1, "Out of Chances"),
  a('Purple', 1, "Spice Up Your Life"),
  //   Level 2
  a('Purple', 2, "Depth Perception"),
  a('Purple', 2, "Double the Fun"),
  a('Purple', 2, "Here We Go Again"),
  a('Purple', 2, "Memory Palace"),
  a('Purple', 2, "Sugar, We're Going Down"),
  a('Purple', 2, "Trophy Room"),
  a('Purple', 2, "Where it Stops, Nobody Knows"),
  //   Level 3
  a('Purple', 3, "A Lengthy Calculation"),
  a('Purple', 3, "A String of Questions"),
  a('Purple', 3, "Array of Sunshine"),
  a('Purple', 3, "For Each Its Own"),
  a('Purple', 3, "I Choose You!"),
  a('Purple', 3, "Objects May Be Larger Than They Appear"),
  a('Purple', 3, "Search Engine"),
  a('Purple', 3, "You'll Fit Right In"),
  a('Purple', 3, "You're Outta Here"),
  //   Level 4
  a('Purple', 4, "A String of Numbers"),
  a('Purple', 4, "Arrays All the Way Down"),
  a('Purple', 4, "Group Project"),
  a('Purple', 4, "Joined at the Hip"),
  a('Purple', 4, "Pop It Like It's Hot"),
  a('Purple', 4, "Together Forever"),
  //   Level 5
  a('Purple', 5, "Calling All Functions"),
  a('Purple', 5, "Feeling Shifty"),
  a('Purple', 5, "Free Fallin'"),
  a('Purple', 5, "Functional Thinking"),
  a('Purple', 5, "Read the Manual"),
  a('Purple', 5, "Time for a Change"),
  //   Level 6
  a('Purple', 6, "Earworm"),
  a('Purple', 6, "Parallax Party"),
  a('Purple', 6, "Path of Least Resistance"),
  a('Purple', 6, "Seven Layer Drip"),
  a('Purple', 6, "Stage Directions"),
  a('Purple', 6, "Stop Motion"),
  a('Purple', 6, "The Choice is Yours"),
  a('Purple', 6, "What's My Line"),

  // Brown belt
  //   Level 1
  a('Brown', 1, "Art Recollecting"),
  a('Brown', 1, "Carefully Curated"),
  a('Brown', 1, "Drop a Pin"),
  a('Brown', 1, "Lights, Camera, Action"),
  //   Level 2
  a('Brown', 2, "A Chain of Reactions"),
  a('Brown', 2, "A Glyph in the System"),
  a('Brown', 2, "Invisible Walls"),
  a('Brown', 2, "Save for Later"),
  a('Brown', 2, "Touch Controls"),
  //   Level 3
  a('Brown', 3, "And the Winner Is"),
  a('Brown', 3, "Checkin' It Twice"),
  a('Brown', 3, "Gravity of the Situation"),
  a('Brown', 3, "Well Rounded Character"),
  a('Brown', 3, "While You're At It"),
  //   Level 4
  a('Brown', 4, "A Refined Palette"),
  a('Brown', 4, "Doppelganger"),
  a('Brown', 4, "Mixing it Up"),
  a('Brown', 4, "Nice Change of Scenery"),
  a('Brown', 4, "Swatch and Learn"),
  //   Level 5
  a('Brown', 5, "Color Wheel"),
  a('Brown', 5, "Depth Perception"),
  a('Brown', 5, "I'm Dithering Away"),
  a('Brown', 5, "Neat n Tidy"),
  a('Brown', 5, "Up to Scale"),
  a('Brown', 5, "Work of Art"),
  //   Level 6
  a('Brown', 6, "Covering All My Bases"),
  a('Brown', 6, "Group By Theme"),
  a('Brown', 6, "The Gang's All Here!"),
  //   Level 7
  a('Brown', 7, "Boing!"),
  a('Brown', 7, "Frame by Frame"),
  a('Brown', 7, "It's Alive!"),
  a('Brown', 7, "Loafin' Around"),
  a('Brown', 7, "Take it For a Spin"),
  //   Level 8
  a('Brown', 8, "A Whole New World"),
  a('Brown', 8, "Changing it Up"),
  a('Brown', 8, "Open Concept"),
  //   Level 9
  a('Brown', 9, "An Asset for Every Season"),
  a('Brown', 9, "Chain of Command"),
  a('Brown', 9, "Choose Your Adventure"),
  a('Brown', 9, "Flavor Text"),
  a('Brown', 9, "Red Light Green Light"),
  a('Brown', 9, "Reliable Narrator"),
  //   Level 10
  a('Brown', 10, "Birds Eye View"),
  a('Brown', 10, "Gauging the Action"),
  a('Brown', 10, "In Depth Image"),
  a('Brown', 10, "Points of View"),
  a('Brown', 10, "Right on Cue"),
  a('Brown', 10, "Wait for the Signal"),

  // Red belt
  //   Level 1
  a('Red', 1, "Hole in One"),
  //   Level 2
  a('Red', 2, "Tower Power!"),

  // Black belt
  //   Level 1
  a('Black', 1, "Something to be Proud Of"),
];

// Belt order is the order of the array, which is curriculum order.
export const STICKER_BELTS = [...new Set(CREATE_STICKERS.map((item) => item.belt))];

export function stickersForBelt(belt) {
  return CREATE_STICKERS.filter((item) => item.belt === belt);
}

// The levels of a belt that carry achievements, in order, each with its own.
// Red and Black have one apiece; Blue Level 4 has nine.
export function levelsForBelt(belt) {
  const out = [];
  for (const item of stickersForBelt(belt)) {
    const last = out[out.length - 1];
    if (last && last.level === item.level) last.stickers.push(item);
    else out.push({ level: item.level, stickers: [item] });
  }
  return out;
}

export function stickerRequirement({ belt, level }) {
  return `Complete ${belt} Belt Level ${level}`;
}
