// GENERATED by scripts/build-module-stickers.mjs. Do not edit by hand.
//
// One sticker per module of JR, Robotics Academy and AI Academy: 38 in all.
//
// NOT ACHIEVEMENTS, and the difference matters. The CREATE book's badges are
// real Code Ninjas achievements, awarded in MakeCode, under the names Code
// Ninjas gave them. There is no equivalent list for these three programs, so
// these are DojoLink's own: the title names the MODULE, written from the
// lessons inside it, and the art is an IMPACT icon the CREATE book did not
// take, shown without its own title because that title belongs to a CREATE
// level. Nothing in the UI calls them achievements.
//
// WHAT A STICKER CLAIMS: that the module is finished — every lesson in it
// logged as Completed. See lib/moduleStickerProgress.js for the one
// definition of "earned".
//
// `moduleName` is the curriculum's real name, placeholders and all ("Module 6",
// "VG 2"), because it is the key: `progress_logs` stores it as text and the
// database is deliberately not renamed. `title` is what a parent reads.

const m = (program, subProgram, moduleName, title) => ({
  id: `${program}-${subProgram}-${moduleName}`.toLowerCase().replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''),
  program,
  subProgram,
  moduleName,
  title,
  get src() { return `/modules/${this.id}.png`; },
});

export const MODULE_STICKERS = [

  // AI Academy
  m("AI Academy", null, "Module 1", "Behind the Curtain"),
  m("AI Academy", null, "Module 2", "Painting by Numbers"),
  m("AI Academy", null, "Module 3", "Ghostwriter"),
  m("AI Academy", null, "Module 4", "Out in the Wild"),
  m("AI Academy", null, "Module 5", "Vibe Check"),
  m("AI Academy", null, "Module 6", "Player Two"),
  m("AI Academy", null, "Module 7", "Brains on Board"),
  m("AI Academy", null, "Module 8", "Trust, but Verify"),
  m("AI Academy", null, "Module 9", "Back to the Drawing Board"),

  // JR · JR Coding
  m("JR", "JR Coding", "Module 1", "One Step at a Time"),
  m("JR", "JR Coding", "Module 2", "Bug Hunt"),
  m("JR", "JR Coding", "Module 3", "Round and Round"),
  m("JR", "JR Coding", "Module 4", "Break It Down"),
  m("JR", "JR Coding", "Module 5", "Step by Step by Step"),
  m("JR", "JR Coding", "Module 6", "On Your Signal"),
  m("JR", "JR Coding", "Module 7", "If You Say So"),
  m("JR", "JR Coding", "Module 8", "First In, First Out"),
  m("JR", "JR Coding", "Module 9", "Two Heads, One Keyboard"),
  m("JR", "JR Coding", "Module 10", "Now You Make One"),

  // JR · Snap Circuits
  m("JR", "Snap Circuits", "Elenco", "Complete the Circuit"),

  // Robotics Academy · LEGO Spike Essentials
  m("Robotics Academy", "LEGO Spike Essentials", "E 1", "Planes, Trains and Swamp Boats"),
  m("Robotics Academy", "LEGO Spike Essentials", "E 2", "A Machine for That"),
  m("Robotics Academy", "LEGO Spike Essentials", "E 3", "Step Right Up"),
  m("Robotics Academy", "LEGO Spike Essentials", "1. Great Adventure", "Great Adventure"),
  m("Robotics Academy", "LEGO Spike Essentials", "2. Amazing Amusement Park", "Amazing Amusement Park"),
  m("Robotics Academy", "LEGO Spike Essentials", "3. Reimagine the World", "Reimagine the World"),
  m("Robotics Academy", "LEGO Spike Essentials", "4. Useful Inventions", "Useful Inventions"),
  m("Robotics Academy", "LEGO Spike Essentials", "5. Animal Friends", "Animal Friends"),

  // Robotics Academy · LEGO Spike Prime
  m("Robotics Academy", "LEGO Spike Prime", "P 1", "Ready, Set, Build"),
  m("Robotics Academy", "LEGO Spike Prime", "P 2", "Reading the Room"),
  m("Robotics Academy", "LEGO Spike Prime", "P 3", "Signed, Sealed, Delivered"),
  m("Robotics Academy", "LEGO Spike Prime", "P 4", "Boot Camp"),

  // Robotics Academy · Ozobot Evo
  m("Robotics Academy", "Ozobot Evo", "O 1", "Color Me Coded"),
  m("Robotics Academy", "Ozobot Evo", "O 2", "Reading Between the Lines"),

  // Robotics Academy · VEX GO
  m("Robotics Academy", "VEX GO", "VG 1", "The Simple Life"),
  m("Robotics Academy", "VEX GO", "VG 2", "Life on Mars"),
  m("Robotics Academy", "VEX GO", "VG 3", "Look, No Hands"),
  m("Robotics Academy", "VEX GO", "VG 4", "Somebody's Got to Do It"),
];

// Every sticker a program has, in curriculum order.
export function stickersForProgram(program) {
  return MODULE_STICKERS.filter((s) => s.program === program);
}
